pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare https://x-token-auth:"$BITBUCKET_VARIABLE"@bitbucket.org/testingworkspace32/testrepo1.git
          - cd testrepo1.git
          - git push --force --all https://x-token-auth:"$GITHUB_VARIABLE"@github.com/manu28042023/test-repo.git
          - git push --force --tags https://x-token-auth:"$GITHUB_VARIABLE"@github.com/manu28042023/test-repo.git
